Deployment fixes
thm-mni-ii/digital-classroom pull request #13
Opened 2021-07-20 22:27 UTC by snicki13

Some adjustments to the deployment process including variables + documentation

2021-07-21 06:52 UTC, mxsph requested changes
Looks good so far :+1: 

However, I would move the `docker-compose.yml` in the `deployment` folder to `examples/docker-compose/docker-compose.yml`.

(Here you should possibly add a `README` with an explanation of use later, but it is not so urgent for now).

2021-07-21 06:57 UTC, mxsph commented
Shouldn't this PR also close ISSUE #12?

2021-08-20 20:17 UTC, snicki13 commented
> Shouldn't this PR also close ISSUE #12?

unfortunately not. This is a configuration issue with Angular. I will focus on it at a later stage of deployment.

2021-08-20 20:22 UTC, mxsph approved these changes

2021-08-20 20:22 UTC, merged