Websockets
thm-mni-ii/digital-classroom pull request #14
Opened 2021-08-29 00:43 UTC by snicki13

RSocket Protocol over WebSockets in place. Users and tickets are refreshed on login and by server push when anything changes.
The client does not need to request updates, they are pushed by the server.

Not yet 100%: 
- UI glitches. -> new branch.
- Conference invitations.
- JWT handling in client needs polishing.

2021-08-30 12:52 UTC, mxsph requested changes
During testing I noticed a couple of errors:

- [ ] Assigning a tutor/lecturer does not work properly yet. For the user who assigns someone, the assignment is displayed and transferred to the server via websoket, but the server does not pass on this information to the other clients and does not save it (after a relaod, no one is assigned anymore).

- [ ] When deleting a ticket, the same error occurs as when assigning it.

- [ ] Making user invisible does not work.
- [ ] Leaving the `digital-classrom` does not work (Button top right). What should happen here anyway?

2021-08-30 12:52 UTC, mxsph commented on src/main/resources/application.yml
> +  host: ${CLASSROOM_HOST:https://localhost:8085}
Since the port is now specified at `CLASSROOM_HOST` is the option `CLASSROOM_PORT` not redundant?

2021-08-30 12:52 UTC, mxsph commented on web-gui/src/app/rsocket/r-socket.service.ts
> +    url: 'wss://localhost:8085/rsocket', //window.origin.replace(/^http(s)?/, 'ws$1') + '/rsocket',
```suggestion
    url: `wss://${window.location.host}/rsocket`,
```

2021-08-30 12:52 UTC, mxsph commented on web-gui/src/app/model/User.ts
>    userRole?: string; // STUDENT, TUTOR or TEACHER
I would also type the role of the user correctly 
e.g. `type UserRole = "STUDENT" | "TUTOR" | "TEACHER"`

2021-08-30 12:52 UTC, mxsph commented on web-gui/src/app/page-components/menu-bar/menu-bar.component.html
> +  <button mat-icon-button class="warn" *ngIf="classroomService.isJoined()" (click)="classroomService.leave()" matTooltip="Online Übungsraum verlassen"><mat-icon >cancel</mat-icon></button>
Since each element is only displayed when `classroomService.isJoined()` you can put them all into one `<ng-container *ngIf="classroomService.isJoined()">` and remove `classroomService.isJoined()` from each condition.

2021-08-30 20:29 UTC, snicki13 commented
> 
> 
> During testing I noticed a couple of errors:
> 
>     * [ ]  Assigning a tutor/lecturer does not work properly yet. For the user who assigns someone, the assignment is displayed and transferred to the server via websoket, but the server does not pass on this information to the other clients and does not save it (after a relaod, no one is assigned anymore).
> 
>     * [ ]  When deleting a ticket, the same error occurs as when assigning it.
> 
>     * ~[ ] Making user invisible does not work.~
> 
>     * ~[ ] Leaving the `digital-classrom` does not work (Button top right). What should happen here anyway?~

1 & 2 are good catches. I missed this. 
3 & 4 are on my list for "Client polishing". I added it. 
The "leave classroom" *should* close the window and cancel all active connections. As you imply the button itself is not really necessary, since the same code is executed when closing the browser tab. That said: I would've gotten to the buttons in my client polishing phase :D

2021-08-30 20:32 UTC, snicki13 commented on src/main/resources/application.yml
> +  host: ${CLASSROOM_HOST:https://localhost:8085}
No. The variable CLASSROOM_PORT specifies the port the embedded HTTP-Server listens to. CLASSROOM_HOST specifies the protocol, host and port the service is reachable with by its users.
In case of the service placed behind a proxy, the ports may be different.

2021-08-30 21:17 UTC, snicki13 commented on web-gui/src/app/rsocket/r-socket.service.ts
> +    url: 'wss://localhost:8085/rsocket', //window.origin.replace(/^http(s)?/, 'ws$1') + '/rsocket',
url: window.origin.replace(/^http(s)?/, 'ws$1') + '/rsocket',
since the websocket security is dependent on the http security.
Good catch.

2021-08-31 21:46 UTC, snicki13 commented
closes #15

2021-09-03 20:08 UTC, mxsph approved these changes
Works so far :+1:

During testing, I noticed two more things that would be useful:

- Option to remove the assignment (#21).
- Option to remove all tickets (#22)

---

While testing with the feedback system I noticed an error (it looks like this error is in the FBS implementation):

It is possible with the following steps to make it not possible to join anymore (500 request in FBS):

- Enter exercise room
- Leave exercise room (close tab)
- Stop the Docker container of the digital exercise room (`docker-compose down`)
- Restart Docker container (`docker-compose up -d`)

(After a restart of the FBS everything works again)

2021-09-03 20:08 UTC, merged