Initial capability to create conferences and join them.
thm-mni-ii/digital-classroom pull request #3
Opened 2021-06-14 23:59 UTC by snicki13

Available functionality:
Create conferences and join via BBB API.
It is possible to configure the feedback system (or probably any BBB Gateway, like Greenlight or PILOS) to connect to the digital classroom instead of a BBB cluster.
Use http://localhost:8085 as address.

When creating a conference from inside the "old digital classroom" in the feedback system, a new tab should open - greeting the user. 

TODO: Code Documentation

2021-06-15 09:23 UTC, mxsph commented on gateway-api.yaml
> +  - url: 'https://localhost:8080/api/v1'
```suggestion
  - url: 'https://localhost:8085/api/v1'
```

The README says to use `https://localhost:8085`, shouldn't that be here too?

2021-06-15 11:48 UTC, snicki13 commented on gateway-api.yaml
> +  - url: 'https://localhost:8080/api/v1'
You‘re right. I just haven‘t updated this for a while. Thank you.

2021-06-15 13:53 UTC, mxsph requested changes
I noticed two errors during the test:

- When opening the `digital-classroom` from the `FBS`, the browser asks for a user name and a password (see `gif`). After some experimenting I found out that the two slashes in the url (http://localhost:8085//api/join?fullName=...) are the problem (this is a bug in the `FBS` but should not lead to a problem).
- If you remove the one slash it works so far, but you are not redirected to the conference (i.e. the welcome message), you just get an xml response. As far as I read in the [BBB specification](https://docs.bigbluebutton.org/dev/api.html#join), the `join` route should redirect to the conference by default and only give an `xml` response if you specify `redirect=FALSE`.

![error](https://user-images.githubusercontent.com/63304184/122064765-af7dc600-cdf1-11eb-8378-8eef703df684.gif)

2021-07-13 08:44 UTC, snicki13 commented
The requested changes were adressed within commits. There are still many open ends, but it is advised to get something relatively stable to the master branch to do first integration tests with PILOS and the FBS.

2021-07-13 15:32 UTC, mxsph requested changes
> There are still many open ends, but it is advised to get something relatively stable to the master branch to do first integration tests with PILOS and the FBS.

:+1: 

I only noticed one more mistake that we should fix before merging. In the `Dockerfile` the `jar` is simply copied into the container. 

https://github.com/thm-mni-ii/digital-classroom/blob/bed214e2a1a88ff6e2e5659076a93ff75889f7d3/Dockerfile#L8

In order for this to work, you have to assemble them beforehand.
I always find this a little unattractive because you then have to have everything installed (furthermore, the current CI/CD will not work with it). I would therefore adapt the `Dockerfile` in such a way that it uses [ multi-stage builds](https://docs.docker.com/develop/develop-images/multistage-build/) and thus assembles the programme in the first stage and copies the `jar` from here.

2021-07-13 15:54 UTC, snicki13 commented
The artifact produced by cradle contains every dependency of the main project. If I understood your inquiry correctly, that was your main concern. 
So you are suggesting to build the artifact within the docker build process?

2021-07-13 16:06 UTC, mxsph commented
> The artifact produced by Gradle contains every dependency of the main project. If I understood your inquiry correctly, that was your main concern.

No. My problem is that in order to build the Docker container, I would have to build the program `local` first and thus have `jdk` etc. installed. Furthermore, I would also need to run two commands to build the container.
 

> So you are suggesting to build the artifact within the docker build process?

Yes, but in order to avoid unnecessary programs (such as the build tools) in the final Docker container, you can use  [ multi-stage builds](https://docs.docker.com/develop/develop-images/multistage-build/).

2021-07-18 20:19 UTC, snicki13 commented
> I noticed two errors during the test:
> 
>     * When opening the `digital-classroom` from the `FBS`, the browser asks for a user name and a password (see `gif`). After some experimenting I found out that the two slashes in the url (http://localhost:8085//api/join?fullName=...) are the problem (this is a bug in the `FBS` but should not lead to a problem).
> 
>     * If you remove the one slash it works so far, but you are not redirected to the conference (i.e. the welcome message), you just get an xml response. As far as I read in the [BBB specification](https://docs.bigbluebutton.org/dev/api.html#join), the `join` route should redirect to the conference by default and only give an `xml` response if you specify `redirect=FALSE`.
> 
> 
> ![error](https://user-images.githubusercontent.com/63304184/122064765-af7dc600-cdf1-11eb-8378-8eef703df684.gif)



> > There are still many open ends, but it is advised to get something relatively stable to the master branch to do first integration tests with PILOS and the FBS.
> 
> 👍
> 
> I only noticed one more mistake that we should fix before merging. In the `Dockerfile` the `jar` is simply copied into the container.
> 
> https://github.com/thm-mni-ii/digital-classroom/blob/bed214e2a1a88ff6e2e5659076a93ff75889f7d3/Dockerfile#L8
> 
> In order for this to work, you have to assemble them beforehand.
> I always find this a little unattractive because you then have to have everything installed (furthermore, the current CI/CD will not work with it). I would therefore adapt the `Dockerfile` in such a way that it uses [ multi-stage builds](https://docs.docker.com/develop/develop-images/multistage-build/) and thus assembles the programme in the first stage and copies the `jar` from here.

fixed

2021-07-18 20:34 UTC, mxsph approved these changes

2021-07-18 20:34 UTC, merged