Fix/conference invitations
thm-mni-ii/digital-classroom pull request #34
Opened 2021-09-09 11:19 UTC by snicki13

2021-09-21 12:16 UTC, mxsph requested changes
During testing I noticed a couple of errors:

- [ ] When you get an invitation, you get the following error message:  `Uncaught (in promise): NotSupportedError: The media resource indicated by the src attribute or assigned media provider object was not suitable.`. This should not be displayed because the browser either does not support this function or the user has rejected the authorization (Thus this error is intentional). Maybe you could add a setting later to activate this function (ask for permission again).
- [ ] The button Make conference invisible does not work.
- [ ] The Exit Conference button does not work. Although the user is removed from the conference in the `digital-classroom`, this user does not actually leave/end the conference. Additionally, this error is displayed: `TypeError: t is undefined `
- [x] The conference list also displays conferences that have already been closed/terminated. Is this intentional? In general I like the idea to show the conferences, later we should probably add better management options here (like ending the conference).
- [x] It looks like it will fix #25 as well?

> Conferences are displayed in frontend (still ugly though)

:+1: Since there are other parts of this application whose design should be adapted in my opinion, I have created an issue for this (#55).

2021-09-22 19:43 UTC, snicki13 commented
The remaining "issues" existed before this PR and will be fixed on another branch within a web-ui overhaul.

2021-09-27 19:15 UTC, snicki13 commented
Let's go!

2021-09-28 06:57 UTC, mxsph requested changes
It is no longer possible to invite someone to a conference: 

- User: When trying to invite a user to a conference this error is displayed `No ticket or conference provided for invitation!`.
- Ticket: When trying to invite a user to a conference no error is shown but the creator of the ticket does not get an invitation.

2021-09-28 06:57 UTC, mxsph commented on web-gui/src/app/page-components/classroom/conferences/conferences.component.ts
> +  }
```suggestion
```

2021-09-28 06:57 UTC, mxsph commented on web-gui/src/app/page-components/menu-bar/menu-bar.component.ts
> +        tap(_ => console.log('kek')),
```suggestion
```

2021-09-28 15:57 UTC, mxsph approved these changes

2021-09-28 15:57 UTC, merged