Logout handling
thm-mni-ii/digital-classroom pull request #69
Opened 2021-10-01 20:19 UTC by snicki13

#44

2021-10-02 06:15 UTC, mxsph requested changes
Looks good so far :+1: There are still a couple of problems though:

- [x] If you specify an external URL (e.g. `www.thm.de`) it is only appended at the end and you are not redirected to it.
  ![logout](https://user-images.githubusercontent.com/63304184/135705830-cd27d133-7bcf-4c24-a356-a34a85128446.gif)

- [ ] Shouldn't a meeting end call to the backend (`/api/end`) be executed the same way as when you press the logout button (i.e. redirect or show the logout page)?

2021-10-03 00:26 UTC, snicki13 commented
> Looks good so far 👍 There are still a couple of problems though:
> 
>     * [ ]  If you specify an external URL (e.g. `www.thm.de`) it is only appended at the end and you are not redirected to it.
>       ![logout](https://user-images.githubusercontent.com/63304184/135705830-cd27d133-7bcf-4c24-a356-a34a85128446.gif)
Fixed! :)
>     * [ ]  Shouldn't a meeting end call to the backend (`/api/end`) be executed the same way as when you press the logout button (i.e. redirect or show the logout page)?
The button is only to let the user leave the classroom. It is not intended to end the classroom instance.

A call to the backend to signal the logout of a user is not necessary, since it is immediately noted with the closed WebSocket-Connection.

2021-10-03 08:23 UTC, mxsph requested changes
> The button is only to let the user leave the classroom. It is not intended to end the classroom instance.
> 
> A call to the backend to signal the logout of a user is not necessary, since it is immediately noted with the closed WebSocket-Connection.

ok :+1: I actually meant it the other way around :smile: When a call is sent to the backend to `/api/end` or when the conference is ended in the backend, the user should notice this in the frontend. Since we now have a function to log out the user in the frontend I thought it would be useful to use this also for this (maybe we should show the user a different text so he doesn't wonder why he was logged out).

2021-10-04 00:43 UTC, snicki13 commented
> 
> 
> > The button is only to let the user leave the classroom. It is not intended to end the classroom instance.
> > A call to the backend to signal the logout of a user is not necessary, since it is immediately noted with the closed WebSocket-Connection.
> 
> ok 👍 I actually meant it the other way around 😄 When a call is sent to the backend to `/api/end` or when the conference is ended in the backend, the user should notice this in the frontend. Since we now have a function to log out the user in the frontend I thought it would be useful to use this also for this (maybe we should show the user a different text so he doesn't wonder why he was logged out).

Like this? :D

2021-10-04 07:31 UTC, mxsph requested changes
When joining I get this error:

```sh
Uncaught (in promise): TypeError: Cannot read properties of null (reading 'getTime') TypeError: Cannot read properties of null (reading 'getTime') at t.startTokenAutoRefresh (https://localhost:8085/static/main.2b8da704a00f7df384c9.js:1:386423) at new t (https://localhost:8085/static/main.2b8da704a00f7df384c9.js:1:384922) at Object.t.ɵfac [as factory] (https://localhost:8085/static/main.2b8da704a00f7df384c9.js:1:386657) at Js.hydrate (https://localhost:8085/static/main.2b8da704a00f7df384c9.js:1:183112) at Js.get (https://localhost:8085/static/main.2b8da704a00f7df384c9.js:1:181028) at Tl.get (https://localhost:8085/static/main.2b8da704a00f7df384c9.js:1:222096) at Object.get (https://localhost:8085/static/main.2b8da704a00f7df384c9.js:1:218986) at Mn (https://localhost:8085/static/main.2b8da704a00f7df384c9.js:1:149184) at Nn (https://localhost:8085/static/main.2b8da704a00f7df384c9.js:1:149972) at ko (https://localhost:8085/static/main.2b8da704a00f7df384c9.js:1:188150)
```

2021-10-04 09:45 UTC, snicki13 commented
You had an JWT without expiry Date in local storage. This is now logged and ends the function. The error unfortunately ended the authentication process, since the first check about a valid JWT is called from a constructor.

2021-10-04 10:53 UTC, mxsph requested changes
Looks good so far :+1:
There is only one bug left:

2021-10-04 10:53 UTC, mxsph commented on web-gui/src/app/rsocket/r-socket.service.ts
> +    return this.connectionStatus.kind === "CONNECTED"
This function always returns false, because `this.connectionStatus` is never set. This leads to the fact that no actions (create ticket etc.) are displayed to the user in the header.

2021-10-04 12:41 UTC, mxsph approved these changes

2021-10-04 12:41 UTC, merged